sudo: false
language: scala
scala:
- 2.12.7
- 2.11.12
before_cache:
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier/cache"
  - "$HOME/.sbt"
jdk:
- oraclejdk8
script:
- sbt ++$TRAVIS_SCALA_VERSION test it:test
env:
  global:
  - secure: RFeJB16BNM3OnHsyVIrneQT6BFJrEymHwy2xKzRSuS8mwVe3JxMKY5JVYL63EDiKBHQ5Ob26K1m2v0WmxMPU1/QySuVElLIk772dO+be75sJ6rzjN6usge4rf3tgFkitEYih1jEyQBb8IF224Br2miUpT2wHDTecIK4PtaVLW1bn1XPLhAuONrn1P/SkwJ5jsRX4tcpnUSFrQYPnnwwhpnHWKiFq5LMuGjdaPyYvcbpTUB6sDzVKbYAuFwDjTc0puGhx1X+tDBZi3QOcMhbvjC7kSHTAR7XkOLCl1Y+S+KGezisC6+65ZU73FvoybhAOR1YG7/4W9XUP2HmIBq79vzZTsRzg3mBDwGXRo+t1xXxKal0eRLvp6uA1bp0GwJxBmBqS5sSp2pgoHPGin3yaTSk1YGlLck0sXOmJdqCdZm5UsICPLaLUTdZ1kAEQgYrDiu5jN0RNQq+UjBS6RtJkNb6HoNYBDYXAI1g3KOKplyLovyIMEogevuDwOzOFdjzTvEVi5tJo5b5IIyJd9bRBLXDZrE8fuwTzUXrnznoV3mnkcyE1udUKDtVwQ9OyRcS/RllrZUvFp3ITQ+wzfb4QYxeKID+IdKX1f84BydU+h6+Jxn/pbmLWT7OLKsBWYfij7nKapUw2f9TXrznANeoyyOdrPp2ogQHElCjq6zAEEVU=
  - secure: Z7b0Weddl6BC6/547eETiXsnXnWxW55dyYMoc7M+3V2Ab84zXEUoXuUEDKYt6v4ZjYiwORxSxs0zYvty6K6EMTNUDyeuIBCAZT5Y4O/fPPxikdOVSOBC0C0ioqs0j4m3bCBzOXnu9rXWgHlNFQoqmpQ3cNVQO/Igskzq7ogcCzB/DASpxDGtQdahgd2nKgkTLdHH9Im5k8MiWJE14f71Z6lSU6b8KKqIQC1htwT8ENet6ADV0en12cAofQHos/4TM1J2x+nJjaxOdEqvMP/0htPn6FFV6WE36euI5qIBkFOQmfQz5O4RjObnIPyRAKFu48xes/j7YByqEmKLNRE1U+P0/uEQzbcJMTacG86VOW0m8XdhrWmOjrUOePS/mifFK4eJpmvg0kFsvUJTdUTOal0UsKSYNE3PrhrTF/bgmPUjp43YAkg5+JZwHDPomWu3sO1/Q7vFPU5cot0acle0p5GLMiWnmuQXo0IV/aHFbtsnyWoGGNVPukoFOSzBQCT9qu8i9i0YKxEq8qEv8XDbhdGAB+vW4yQsrJaQhxaEYy+2/5cD8ggX3/SFq1IX470lO/VK9jN6QxP1PTuoeeiluT4i11Vcusu9BsmA9xdrxPLg/r1lu+CMtiurjKn94wBrmlrTYTt2xCamDG1Bg7xUMKtl4hkTXPoLVjzseW5EADk=
  - secure: jY5LBRH3AA4scyj7iiUXzjgxt9vV0UYShp/6aoObUy2Nq/K8vBlF3bdcVifEbQ4ie9BVo0xrlrY9PltpbTJSSWhRIwcYPOqafS6RwiaN3/0/7ZHA8Ic8oVX5Bi3Bb+nD/CbaHVonDFKMobqeB0u9a8My7EVh69tqHkGLTh3RsVJE76uS5TPuCcDyMxuDXT9g3LpuCuEkGwYnIzqg8jj1SynY2IxHBp9PMANE3QPdAqI+QwE7nCbtOFUOl0Iz2VqMCf6I4puAb+zp3FBsKp3sLa8gU//BAAZra89ZkBTK7Sg1y76jL5giGizmKOH2bfKmgwsvY+Xsk2CfHFkzoFHI5iHTIihs5yqkcUA6HkdMI6ryDspbu2OcXiE/8+3DhGpyB+of4mEk/ptgWRXQXhnTRkQh8qjKWj2y0tu5iBofIM8AjBD35kO8bUe2farACFSxMlGZKYlC56OSEajowN7CBy9vD9wjskSHM60xj0Lgcp9BUBOtR3znuR0j9DizwSq9KRlHjaMAh8IAhbpbbJjhM1JdtJJ9UtoH4PnaYP84qP4FjVDQl3p1QFV1iDrHaHXfr1uKMF3Z0I2OIvaBrQNwxnTrXyPhLsSI37blFqoawVnzZLPn2VkZoyi/Gv65eJ9HYq5XiAdNSu+aDAfRppSS/+Naz5S57jQTBrGE9HI6W3M=
