sudo: false
language: scala

scala:
- 2.12.7
- 2.11.12

before_cache:
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier/cache"
  - "$HOME/.sbt"

jdk:
- oraclejdk8

script:
- sbt ++$TRAVIS_SCALA_VERSION test it:test

env:
  jira4s:
  - secure: hbwXBDVoPhJMAbbCWz7Vrs4mXDSH/I16FuoC5AG5kOj5uzkqX2aoDN8rJeYvB6gHOc4uPAfil//1ADYqLTk8nfbIWPyCQjRAbd+X8ORAdulyFgsFJvfmGBMzDY/5Y82ErvM+SCY6Sx82opCn918vFuri5QWa9nKMt6D702ZeQ3kAkyuU3z6fpKANTrXlaJZF8T6hI45d58pUxq2hmiocI7il2d+EB/6Ke7OCajgTvsNKejFKvSESAM6pIuy2C/zdxIEiBF9CYi/E3/IGFURtK8F+07oUba7qqwtSu+Maq9SPAdSYbC1nOkFDIuOxdGUdHHoQbN/FrcJxU7V0Yz9crpCHlNWVCRYlSacCjxneIUZzM07yJiYjaChxw+Fk6zl8/PWvNIUlB9C4Pc67VHPAktUCftRf7eGwNzI22gHhNyfy2CDEKBIepdtzwZIK1rzkqtJ6Bd9gxF7XJtILyShRaf9+4R3qipCfqVt7yzWiFIXolm/LRYZ+6uZFTlqpC5CcQzsM1Igp9ybuJ5uNB5TsbL36biY68sEsZZoeoEc+inASwDhIft35Zr8ux92uBgSSYtTwwiMw4O57EYg0GpxGRjbSuadw4FSoBDU2J/HE2pa4gs8Gt/FU/mfz+26MgEHp5ti6y7ABXwr6AcmdrbiMQTyP8TL+nEiZ77JG2ZLGkt0=
  - secure: KQPqQ0rP3tYskAwQmoRzDkjfwhEiIGNSjyBDTLq43YmMgd1BDZZX2TapYUT9kMaqFe5loUNOknCXMqvWH+duvQU1P2gJx0/b7aIfsd/K9MePzj+nmd97JbXlzFj6dLdccACO0o3U/x2G+Ef53waurqPDsYzqo8f3X6itF1OwFqn/gPnxfrQdf3UrSqb7TEuIDNiJ0EX/LpJygKNPobBzbXLli8yalmG7cbSSuGKb3W4poHlvqFQuoUKKS7QcoFOS2z5pyusR+TJqp+KXfNf0sjBgUuNZJsQH3WVUuGKx8r7kFafERHbbxP0P6Lpg/f3eQb/lzMl2nndSFqEzhgyR2buSGiIfSbV1NbJaBmk4MlgTbqG0gY+HqIUZynBrRrZyuHRNl9PktFG0Fd3SEte2V/KDJ/4J3ApK/z9i+NzybU1telVUiWOf3RuTTiS4SMdsbvV9j2vWU3zF/UU074Q7hDcYD8hu9Zv8A3wn5Y3ZUhO7EGAA3hFF45l8ysLsmV9LmmJrfUmwTpxhDmTmXGHiu2rcBV2IeLC3kl1rF+7uZaIgGBTwvZkpWR2k2nAxYMNGpNl8knI7PxyKscbvHNvXWZ5nNLgYDQpMhTmtcaV0uVV6ROvfqFyLV80UzCBvQSmni7EnbP94XBQD/5REnWOz4tcerdk/DPUWEh6HbcRT1WE=
  - secure: AqsjTIFEKxTYM66NHezd70ytLPiRwXgcJMcz0qC/RXNr4nHsjcRmxyOmDFiSbAB5K06bSRfLdrQOxtXRlgaDMFZHAj+f0Wa+/KgkplNNkb7IHNX4bLFOhgOvl6JbrhEzgYFQUZBZ4UCVvOAEHEFmHcidX9B9yFZZb19WI9o6RBlJ5puWVUSI6zVLgzU3xjjTbnspuJB6sgm8bsRSfvfkO+ejB+3zLAd6eeDmypucseRVNicqK7iWS8uC03qDEeqGr6+az8l/UtQ9BtiBfm5siGkyAGTSvSR2XlP7iDpkWIXL8yEhHGIy1aniE/YIXN7VXh3zoWbGimI9Y+ArJIUZ2K3u+zYjDX6uFMJswaCQ9DHl35+FlEXwVtRewbwtLCMxdWNSFWCWdo0yLYeNMgQarzueRUil3WLtISq3iEeeH08C7Qp3aQE1xq/+x5NfYNDybFCraILJGWNJMt0Rrv9yz+f5nNyX4i/LwTzgHDniBJrTFM5Q3HRyoRWq0CKOWdBnIm+vxZ3S3APlhZHDx9IsUXaI54BbIuoRRs3U2nwCMSYz8Fem1F/FfYQeRa6cVOfl2ECZZ1TBlRVV8XuYcJ9vwcwL+kZvDMpePS9LV2CZ7r3Xo8fwlZ8zVQi73chKr1oWzlKRdUXsEdM91chaKWI+T6vm69VXLuODYAyZwbhy92g=
